version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: msbuild src\NLog.MailKit.sln /t:restore
build:
  project: src/NLog.MailKit.sln
  verbosity: minimal
test_script:
- ps: dotnet test test\NLog.MailKit.Tests\NLog.MailKit.Tests.csproj
artifacts:
- path: src\NLog.MailKit\bin\Release\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: DtVDH1ZfIR8E2oDLeSPxfn0WFXw3MCv4WhLkkQQl9LfEHswb5sdxdCYodNKhrKik
  artifact: /.*\.nupkg/
  on:
    branch: master