name: '$(Rev:r)' # Build.BuildId
trigger:
- master
pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  Solution: 'src/NLog.MailKit.sln'
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '$(Solution)'
    verbosityRestore: Minimal

- task: SonarCloudPrepare@3
  displayName: 'Prepare SonarCloud analysis'
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: nlog
    projectKey: nlog.mailkit
    projectName: 'NLog Mailkit'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '$(Solution)'
    msbuildArgs: '-v:m -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:ContinuousIntegrationBuild=true -p:EmbedUntrackedSources=true'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    maximumCpuCount: true
    logProjectEvents: false

- task: VSTest@2
  displayName: 'Run Tests'
  inputs:
    testAssemblyVer2: |
     **\*.tests.dll
     !**\obj\**
     !**\ref\**
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    rerunFailedTests: true

- task: SonarCloudAnalyze@3
  displayName: 'Run SonarCloud Analysis'

- task: SonarCloudPublish@3
  displayName: 'Publish SonarCloud Quality Gate'
