name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/NLog.MailKit.sln

      - name: Build
        run: dotnet build src/NLog.MailKit.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test src/NLog.MailKit.sln --configuration Release --no-build

      - name: Pack
        if: matrix.os == 'windows-latest'
        run: dotnet pack src/NLog.MailKit.sln --no-build --configuration Release --output artifacts

      - name: Upload nuget package
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: artifacts/*.nupkg

      - name: NuGet login
        if: github.ref == 'refs/heads/master' && matrix.os == 'windows-latest'
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push to NuGet.org
        if: github.ref == 'refs/heads/master' && matrix.os == 'windows-latest'
        shell: bash
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
